language: node_js

node_js:
  - node

addons:
  apt:
    packages:
      - xvfb
      - libusb-1.0-0-dev

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn config set cache-folder $HOME/.cache/yarn

install: yarn

stages:
  - lint
  - depcheck
  - test
  - e2e

before_script:
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; sleep 3; fi'

script:
  - yarn test:unit:coverage --ci --maxWorkers 4

jobs:
  include:
    - stage: lint
      script: yarn run lint

    - stage: depcheck
      script: yarn run depcheck

    - stage: e2e
      script: yarn run test:e2e

cache:
  yarn: true

git:
  # It's not necessary to get more than the last commit (and this branch alone)
  depth: 1
