language: node_js

node_js:
  - 9

env:
  - CXX=g++-4.8

addons:
  apt:
    packages:
      - xvfb
      - build-essential
      - git
      - gcc-4.8
      - g++-4.8
      - libusb-1.0-0
      - libusb-1.0-0-dev
      - libudev1
      - libudev-dev

cache:
  yarn: true

install:
  - yarn

stages:
  - lint
  - depcheck
  - unit-test
  - e2e-test

before_script:
  - yarn global add node-gyp
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; sleep 3; fi'

jobs:
  include:
    - stage: lint
      script: yarn run lint
    - script: yarn run depcheck

    - stage: unit-test
      script: yarn test:unit:coverage --ci --maxWorkers 4

    - stage: e2e-test
      script: yarn run test:e2e

git:
  # It's not necessary to get more than the last commit (and this branch alone)
  depth: 1
